### ISSUE TITLE
Add version flag

### ISSUE THREAD

**Issue by ignaciot** [Dowell-Lab/DAStk#13]
Add the standard -v/--version flag to inquiry the current tool version. Is there a way to pick this up automagically from the PyPi configuration?

**Comment by magruca** [comment]
The easiest way to do this is using yolk3k... which is an option but requires another package. It is in conda though for when we develop that

**Comment by magruca** [comment]
Decided to add this using argparse function instead which will mean manual editing with pushes, but now implemented
