### ISSUE TITLE
Add window size flag

### ISSUE THREAD

**Issue by andrewbcaldwell** [Dowell-Lab/DAStk#14]
Would it be possible to add a flag to adjust the window size beyond the standard +/-1500bp? Thanks!

**Comment by magruca** [comment]
This would be easy enough to do and we've toyed the idea of going back and looking at alternative window sizes and alternative window types in general. In our first pass at the MD score analysis (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5848612/) we found that the majority of published motifs fall within 300bp of the center (mu) of the bidirectional call from using Tfit, thus informing our decision to use the 300/3000bp window centered around the feature of interest.

If you expand the +/-1500, then you also need to expand/adjust the center to keep your background value at 0.1, also easily doable as long as the window is centered. If you start expanding the window too much, however, you'll tend to always just get random noise, quite a bit moreso if you loosen the stringency on your motif scanner.

That said, in future versions, we are probably going to add a few more features to better capture some of the other motif patterns that we see (e.g. RUNX1 has strong co-localization about 500bp+/- offset from the center of a bidirectional), but this again also requires an adjustment as to how the background is calculated.   

I'll look into this a little bit more as we've made some adjustments to our processing pipeline for both nascent and ATAC data, but we're probably fine adding a flag for this on the next release.

**Comment by magruca** [comment]
@andrewbcaldwell -r/--radius argument added in v0.3.0 that will allow you to change the window size. More details are included in the README. Keep in mind, in all of my test cases, this will typically just result in an MD score approaching background (0.1)
