### ISSUE TITLE
Ability to manually provide genome description

### ISSUE THREAD

**Issue by ignaciot** [Dowell-Lab/DAStk#17]
The current listing of chromosomes is pulled from UCSC genomes, which is not a complete repository. Most plant genomes, for example, are missing. So we need to add an optional parameter to pass a comma-separated list of chromosomes for the genome in question, in which case we ignore the UCSC query.

**Comment by magruca** [comment]
Addressed this a little differently. I decided to add an argument (-c/--chromosomes)  where the user can provide a chromosome sizes file which can be generated easily using samtools or even downloaded from UCSC as we do internally with the -g/--genome flag. The instructions for generating it using samtools are included in the README. This is tested and working and pushed to a bug fix branch which will get merged in after I address some of the other issues.

**Comment by magruca** [comment]
Updated and fixed in v0.3.0
