### ISSUE TITLE
Incorrect Shebang for Executables

### ISSUE THREAD

**Issue by zmaas** [Dowell-Lab/DAStk#25]
Some files contain an incorrect shebang directive on the first line. The directive in the current source code is `#! /usr/bin/env/python` when it should be `#!/usr/bin/env python`. This causes execution to fail when scripts are invoked directly as executables.

This issue affects the following files:
- differential_md_score.py
- process_atac.py

**Comment by magruca** [comment]
Fixed in release 0.3.2
