### ISSUE TITLE
Columns produced by differential_md_score function

### ISSUE THREAD

**Issue by TobyGurran** [Dowell-Lab/DAStk#29]
Hi,

Thanks for the great package!

I just wanted to ask, what are the output columns from the `differential_md_score` function please?

e.g.

`
                     V1 V2     V3    V4    V5    V6    V7 V8

1  CTCF_HUMAN.H11MO.0.A  1 123467 13580 13580 0.574 0.574  0

2   JUN_HUMAN.H11MO.0.A  1  71882   584   584 0.538 0.538  0

3  JUND_HUMAN.H11MO.0.A  1  77086  1138  1138 0.525 0.525  0

4 FOSL2_HUMAN.H11MO.0.A  1  77543  1024  1024 0.484 0.484  0

5 NF2L2_HUMAN.H11MO.0.A  1  84127  1043  1043 0.481 0.481  0

6 BACH2_HUMAN.H11MO.0.A  1  86993  1314  1314 0.472 0.472  0`

**Comment by magruca** [comment]
Apologies that does need to be added to the documentation. In order:
motif \t total number of motif hits \t number of hits in sample 1 \t number of hits in sample 2 \ md score sample 1 \t md score sample 2 \t differential md score

**Comment by TobyGurran** [comment]
Perfect! Thanks very much :-)

**Comment by ignaciot** [comment]
Thanks, Margaret! Just an update, there's a column missing in the above description (2nd column), which is the p-value (which is 1.0 in the example rows Toby cited, meaning those are insignificant changes). I'll update the README with the new column description.
