### ISSUE TITLE
Invalid links for the pre-scanned motif files 

### ISSUE THREAD

**Issue by jcbusch** [Dowell-Lab/DAStk#34]
Would it be possible to fix the links for the the pre-scanned motif files? Or at least include more details about the file format? I'm currently running FIMO to make my own but I want to make sure it's creating the correct file type/format before using.

**Comment by ignaciot** [comment]
Thanks for bringing that up, I was not aware that the pre-processed motif storage link was no longer functional. While I check that out, the motif files have a `.bed` extension and consist of simply 3 TAB-separated columns:

`CHROMOSOME <TAB> Start position <TAB> End position`

**Comment by lynn-sanford** [comment]
These files are no longer hosted through the Dowell lab website. I instead uploaded them to Zenodo (https://doi.org/10.5281/zenodo.8432115) and updated the link in the README accordingly. Let me know if you have any other issues accessing them!
