### ISSUE TITLE
Issue while trying to generate MA plot and barcode plot. PLEASE HELP!

### ISSUE THREAD

**Issue by Divya6805** [Dowell-Lab/DAStk#36]
Another error encountered with different files! I am trying to analyze ATAC-seq data for the first time and would appreciate timely help.
![Screenshot 2023-11-25 122003](https://github.com/Dowell-Lab/DAStk/assets/151932729/4c522ddf-f857-4a66-a13b-3593d66b5a22)

**Comment by ignaciot** [comment]
This one looks like an argument that got deprecated in the later versions of matplotlib, the library used to generate figures. Should be an easy fix, in the meantime you can downgrade to an older version. E.g., 

```
$ pip uninstall matplotlib
$ pip install matplotlib==3.5.1
```

**Comment by Divya6805** [comment]
Thank you ! I had changed from basex= 2 to base =2 in line 298 in differential_md_score.py and it worked.

**Comment by ignaciot** [comment]
Changed this in the code to support the later matplotlib versions.
