### ISSUE TITLE
try alternative to pooled variance

### ISSUE THREAD

**Issue by magruca** [Dowell-Lab/DAStk#6]
In scenarios where there are large differences between total number of sites between control/treatment comparisons in differential MDS (often observed in ChIP with highly-specific antibodies), even with a large change in MD score, this significance is currently lost using the pooled variance correction. It may be useful to try an alternative approach such that these sites are not lost using a normal correction. If the number of sites between the two samples are relatively similar, the calculated p-values should be nearly the same as using the pooled variance -- can probably use the zinc fingers as control tests between the two methods.

**Comment by magruca** [comment]
Currently testing in bootstrap branch

**Comment by ignaciot** [comment]
Fixed in 0.2.0.
